version: '3'

services:
  drupal:
    image: drupal
    ports:
      - "81:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal

volumes:
  drupal_data:
  mysql_data:
